name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login
        npm install
        npm run build
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"
        git add -f dist && git commit -m "Building GitHub page"
        git subtree push --prefix dist origin gh-pages