name: Build

on:
  push
permissions:
  actions: write
  contents: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and publish
      run: |
        # gh auth login --with-token ${{ secrets.GITHUB_TOKEN }} 
        npm install
        npm run build
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"
        git add -f dist && git commit -m "Building GitHub page"
        git push origin `git subtree split --prefix dist main`:gh-pages --force
        # git subtree push --prefix dist origin gh-pages